### PR TITLE
Remove bounded contexts, Replace UML diagram (4.)

### PR DESCRIPTION
**Pull request by SvetlanaIvanovic**
* Remove redundant bounded contexts under 4. because it is in 3. 
* Replace UML diagram with a webp file, so the resolution is sharper 
* Is that ok like so?

### CODE REVIEW

**Comment by futurefounder** [comment]
Thanks for the updates @SvetlanaIvanovic. Could you kindly also update the pdf and add it to the pr? Then it can be merged from my view.

**Comment by Orock237** [comment]
Well done

**Review by CodeGlitter — CHANGES_REQUESTED** [review]
I noticed a couple minor mistakes in our text description (see attached photo).
If you could fix these as suggested before merging, I think we're good to go.

**Comment by SvetlanaIvanovic** [comment]
I have updated the file according to your change request @Emma. If ok, please feel free to merge @Emma, @futurefounder, @Orock237.

**Review by CodeGlitter — APPROVED** [review]

**Comment by CodeGlitter** [comment]
Good work, thank you! As the overall changes were approved, I am now merging this PR.

**Pull request merged**
