### PR TITLE
Add feature/aufg3 klassendiagramm

### PR DESCRIPTION
**Pull request by CodeGlitter**
Hi guys,
this is to add the class diagram to our repository. It's part 1 of my assigned tasks.

### CODE REVIEW

**Comment by futurefounder** [comment]
@CodeGlitter the new readme looks different from the last one on main. maybe exclude the readme from this PR and just push your image?

**Comment by Orock237** [comment]
I find the class diagram difficult to read. 

image

I would recommend using a tool that is suitable for UML diagrams.  Please use @SvetlanaIvanovic 's class diagram as an example.
image

**Review by Orock237 — CHANGES_REQUESTED** [review]
I find the class diagram difficult to read. 
I would recommend using a tool that is suitable for UML diagrams.

**Comment by SvetlanaIvanovic** [comment]
Hi, I understood that at this stage of the tasks on the exercise sheet, it does not have to be overly formal (no formally correct UML class diagram required) - so as a sketch it is probably fine. But maybe one thing, that I would suggest to simplify the diagram and increase readability, without having to make it completely new, since we have it later on in a more formal way in task 4 anyways: the connectors could be changed to simple arrows. What do you think about these thoughts and approach @Orock237 , @CodeGlitter, @futurefounder ?

**Comment by futurefounder** [comment]
Good point @SvetlanaIvanovic  I also think no tool needed, but it would help and be more according to the task if the overview is simplified, as the task reads

> Output: Erstellen Sie ein **einfaches Klassendiagramm**, das das Domänenmodell darstellt.

**Review by SvetlanaIvanovic — APPROVED** [review]
From my side approved.

**Pull request closed without merging**
