### PR TITLE
Add solution to Übungsblatt 3, Aufgabe 4

### PR DESCRIPTION
**Pull request by SvetlanaIvanovic**
Added solution to task 4 about entities and aggregates. Can you please provide your feedback before it is merged?

### CODE REVIEW

**Comment by Orock237** [comment]
Good job!

The entities **_Bürger_** and _**Mitarbeiter**_ have the same attributes and methods. I think it would be better to create an entity _**Benutzer**_ with the additional attribute _**Role**_, which can have the following values:  _**Bürger**_, _**Mitarbeiter**_ and _**Administrator**_.

What do you think about @futurefounder , @CodeGlitter  ?

image

**Comment by SvetlanaIvanovic** [comment]
> Good job!
> 
> The entities **_Bürger_** and _**Mitarbeiter**_ have the same attributes and methods. I think it would be better to create an entity _**Benutzer**_ with the additional attribute _**Role**_, which can have the following values: _**Bürger**_, _**Mitarbeiter**_ and _**Administrator**_.
> 
> What do you think about @futurefounder , @CodeGlitter ?
> 
> image

Thanks for the feedback! I like the idea to reduce redundancy and maintenance efforts by combining those similar entities. 

Probably, when we get to the implementation, it would make sense to solve that via inheritance - does it? A base class benutzer with the attributes and methods that are the same for all roles, and then subclasses bürger, mitarbeiter, admin (with their additional, individual attributes and methods).

**Comment by Kem-IT** [comment]
Yeah nice idea! We can do it 👍🏿

**Comment by Orock237** [comment]
Yeah nice idea! We can do it 👍🏿

**Comment by futurefounder** [comment]
Great Idea @SvetlanaIvanovic and @SvetlanaIvanovic, I think your thoughts make total sense

**Pull request closed without merging**
